### PR TITLE
Fix typos in Mech descriptions

### PR DESCRIPTION
**Pull request by vks**

### CODE REVIEW

**Comment by BlueWinds** [comment]
These corrections all look good.

BloodyDoves is fairly particular about pull requests, and generally prefers that people contact the team before / while making them. Hit me up on discord (BlueWinds#1516) and talk make sure not to ruffle his feathers in the future. :)

**Review by BlueWinds — APPROVED** [review]

**Comment by vks** [comment]
> BloodyDoves is fairly particular about pull requests, and generally prefers that people contact the team before / while making them. Hit me up on discord (BlueWinds#1516) and talk make sure not to ruffle his feathers in the future. :)

That's fair and understandable. May I suggest adding a `CONTRIBUTING.md` mentioning that? It will even make GitHub show a popup to everyone opening a PR for the first time (see [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Seems like the best way to avoid unintentional feather ruffling. If there is interest, I can make a PR, but I guess I should discuss this on Discord.

**Comment by BlueWinds** [comment]
Yeah, I made the same suggestion in our team chat when it came up. :) I'll get one added soon here.

**Comment by bloodydoves** [comment]
I'll merge this based on your conversation with Blue. We also have the relevant CONTRIBUTING.md file in place now. Next time, please contact me before randomly sending a PR, at least to let me know you're looking at it and/or found something to improve.

**Pull request merged**
